/**
 * Official Swiss Licence Categories Data (VZV SR 741.51 / asa statutory standard)
 * 12 categories fully documented in 4 languages (DE, FR, IT, EN).
 */
const SWISS_CATEGORIES_DATA = [
  {
    code: 'B',
    displayCode: 'B',
    icon: '🚗',
    nameDe: 'Personenwagen',
    nameFr: 'Voitures de tourisme',
    nameIt: 'Autovetture',
    nameEn: 'Passenger Cars',
    subtitleDe: 'Motorwagen bis 3.5 t und max. 8 Personen (ausser Fahrer)',
    subtitleFr: 'Véhicules automobiles jusqu\'à 3,5 t et max. 8 places',
    subtitleIt: 'Autoveicoli fino a 3,5 t e max. 8 passeggeri',
    subtitleEn: 'Motor vehicles up to 3.5 t and max. 8 passenger seats',
    minAge: 17,
    questionCount: 50,
    durationMinutes: 45,
    maxErrorPoints: 15,
    maxScore: 150,
    passRate: '90%',
    questionTypeDe: 'Multiple-Choice (1 oder 2 richtige Antworten pro Frage)',
    questionTypeEn: 'Multiple-Choice (1 or 2 correct answers per question)',
    examTypeDe: 'Basistheorie (asa Prüfungsmodus)',
    examTypeEn: 'Basic Theory (official asa mode)',
    legalBasis: 'VZV Art. 3 Abs. 1; SVG Art. 10',
    validityMonths: 24,
    vkuRequiredDe: 'Ja, Verkehrskundeunterricht (VKU) obligatorisch (8 Std.)',
    vkuRequiredEn: 'Yes, Traffic Safety Theory course (VKU, 8 hours)',
    descDe: 'Die Basistheorieprüfung für Kategorie B umfasst 50 Fragen im Multiple-Choice-Verfahren. Bei maximal 15 Fehlerpunkten gilt die Prüfung als bestanden. Mit bestandener Basistheorie erhalten Sie den 24 Monate gültigen Lernfahrausweis.',
    descEn: 'The Category B basic theory examination consists of 50 multiple-choice questions. A maximum of 15 error points is allowed to pass (90% required). Passing grants a learner permit valid for 24 months.'
  },
  {
    code: 'A',
    displayCode: 'A',
    icon: '🏍️',
    nameDe: 'Motorräder unbeschränkt',
    nameFr: 'Motocyles sans restriction',
    nameIt: 'Motociclette non limitate',
    nameEn: 'Motorcycles Unlimited',
    subtitleDe: 'Motorräder mit mehr als 35 kW Motorleistung',
    subtitleFr: 'Motocyles d\'une puissance supérieure à 35 kW',
    subtitleIt: 'Motociclette con potenza superiore a 35 kW',
    subtitleEn: 'Motorcycles with engine power exceeding 35 kW',
    minAge: 20,
    questionCount: 50,
    durationMinutes: 45,
    maxErrorPoints: 15,
    maxScore: 150,
    passRate: '90%',
    questionTypeDe: 'Multiple-Choice (1-2 richtige Antworten)',
    questionTypeEn: 'Multiple-Choice (1-2 correct answers)',
    examTypeDe: 'Basistheorie (sofern nicht bereits für B bestanden)',
    examTypeEn: 'Basic Theory (unless already passed for Cat B)',
    legalBasis: 'VZV Art. 3 Abs. 1 & Art. 15',
    validityMonths: 4,
    vkuRequiredDe: '12 Stunden praktische Grundschulung (PGS) obligatorisch',
    vkuRequiredEn: '12 hours practical basic motorcycle training (PGS)',
    descDe: 'Für den Direkteinstieg oder Aufstieg nach 2 Jahren klagloser Fahrpraxis in Kategorie A beschränkt (35 kW). Praktische Führerprüfung erforderlich.',
    descEn: 'Available after 2 years of holding category A limited (35 kW). Requires 12 hours practical rider training and official cantonal road exam.'
  },
  {
    code: 'A35',
    displayCode: 'A 35 kW',
    icon: '🏍️',
    nameDe: 'Motorräder beschränkt',
    nameFr: 'Motocyles limités',
    nameIt: 'Motociclette limitate',
    nameEn: 'Motorcycles up to 35 kW',
    subtitleDe: 'Motorleistung max. 35 kW und max. 0.20 kW/kg Leistungsgewicht',
    subtitleFr: 'Puissance max. 35 kW et max. 0,20 kW/kg',
    subtitleIt: 'Potenza max. 35 kW e max. 0.20 kW/kg',
    subtitleEn: 'Engine power up to 35 kW and max 0.20 kW/kg ratio',
    minAge: 18,
    questionCount: 50,
    durationMinutes: 45,
    maxErrorPoints: 15,
    maxScore: 150,
    passRate: '90%',
    questionTypeDe: 'Multiple-Choice',
    questionTypeEn: 'Multiple-Choice',
    examTypeDe: 'Basistheorie',
    examTypeEn: 'Basic Theory',
    legalBasis: 'VZV Art. 3 Abs. 1 & Art. 15',
    validityMonths: 4,
    vkuRequiredDe: '12 Stunden Grundschulung + VKU',
    vkuRequiredEn: '12 hours practical training + VKU',
    descDe: 'Die Stufe für Motorrad-Fahranfänger ab 18 Jahren. Nach 2 Jahren Besitz kann prüfungsfrei oder mit praktischer Prüfung auf unbeschränkt A aufgestiegen werden.',
    descEn: 'Motorcycle entry category at 18 years. Learner permit valid for 4 months, extended by 12 months upon completing the 12-hour basic course.'
  },
  {
    code: 'A1',
    displayCode: 'A1',
    icon: '🛵',
    nameDe: 'Leichtmotorräder',
    nameFr: 'Motocyles légers',
    nameIt: 'Motocicli leggeri',
    nameEn: 'Light Motorcycles',
    subtitleDe: 'Bis 125 ccm und max. 11 kW (ab 15 Jahren bis 50 ccm / 4 kW)',
    subtitleFr: 'Jusqu\'à 125 cm³ et max. 11 kW (dès 15 ans pour 50 cm³)',
    subtitleIt: 'Fino a 125 cm³ e max. 11 kW (da 15 anni per 50 cm³)',
    subtitleEn: 'Up to 125 cc and max 11 kW (from age 15 for 50 cc / 4 kW)',
    minAge: 15,
    questionCount: 50,
    durationMinutes: 45,
    maxErrorPoints: 15,
    maxScore: 150,
    passRate: '90%',
    questionTypeDe: 'Multiple-Choice',
    questionTypeEn: 'Multiple-Choice',
    examTypeDe: 'Basistheorie',
    examTypeEn: 'Basic Theory',
    legalBasis: 'VZV Art. 3 Abs. 2',
    validityMonths: 4,
    vkuRequiredDe: '12 Stunden praktische Grundschulung',
    vkuRequiredEn: '12 hours practical training',
    descDe: 'Ermöglicht das Fahren von 50 ccm Roller ab 15 Jahren sowie 125 ccm Motorrädern ab 16 Jahren. Gleiche 50 Theoriefragen wie bei Kategorie B.',
    descEn: 'Permits 50 cc mopeds from age 15 and 125 cc motorcycles up to 11 kW from age 16. Uses the identical 50-question federal Basistheorie exam.'
  },
  {
    code: 'C1',
    displayCode: 'C1',
    icon: '🚚',
    nameDe: 'Leichte Lastwagen',
    nameFr: 'Camions légers',
    nameIt: 'Autocarri leggeri',
    nameEn: 'Light Trucks',
    subtitleDe: 'Motorwagen über 3.5 t bis max. 7.5 t Gesamtgewicht',
    subtitleFr: 'Véhicules de plus de 3,5 t à 7,5 t',
    subtitleIt: 'Autocarri tra 3,5 t e 7,5 t',
    subtitleEn: 'Motor vehicles between 3.5 t and 7.5 t total weight',
    minAge: 18,
    questionCount: 30,
    durationMinutes: 45,
    maxErrorPoints: 3,
    maxScore: 30,
    passRate: '90%',
    questionTypeDe: 'Single-Choice (genau 1 richtige Antwort)',
    questionTypeEn: 'Single-Choice (exactly 1 correct answer)',
    examTypeDe: 'Zusatztheorie C1/D1',
    examTypeEn: 'Additional Theory C1/D1',
    legalBasis: 'VZV Art. 3 Abs. 2; ARV 1',
    validityMonths: 24,
    vkuRequiredDe: 'Voraussetzung: Vorbesitz Führerausweis Kat. B',
    vkuRequiredEn: 'Prerequisite: Valid category B driver licence',
    descDe: 'Spezifische Zusatztheorieprüfung mit 30 Fragen zu Gewichtslimiten, Ladungssicherung, Abmessungen und den Arbeits- und Ruhezeitvorschriften (ARV 1). Maximal 3 Fehler erlaubt.',
    descEn: 'Specific 30-question single-choice exam covering axle loads, dimensions, cargo securing, tachographs and drivers working hours (ARV 1). Max 3 errors allowed.'
  },
  {
    code: 'C',
    displayCode: 'C',
    icon: '🚛',
    nameDe: 'Schwere Lastwagen',
    nameFr: 'Poids lourds',
    nameIt: 'Autocarri pesanti',
    nameEn: 'Heavy Trucks',
    subtitleDe: 'Schwere Motorwagen mit Gesamtgewicht über 3.5 t',
    subtitleFr: 'Véhicules automobiles lourds de plus de 3,5 t',
    subtitleIt: 'Autocarri di peso complessivo superiore a 3,5 t',
    subtitleEn: 'Heavy goods vehicles with total weight over 3.5 t',
    minAge: 18,
    questionCount: 40,
    durationMinutes: 60,
    maxErrorPoints: 4,
    maxScore: 40,
    passRate: '90%',
    questionTypeDe: 'Single-Choice',
    questionTypeEn: 'Single-Choice',
    examTypeDe: 'Zusatztheorie C/D',
    examTypeEn: 'Additional Theory C/D',
    legalBasis: 'VZV Art. 3 Abs. 1; CZV',
    validityMonths: 24,
    vkuRequiredDe: 'Voraussetzung: Vorbesitz Kat. B; Vertrauensärztliche Untersuchung',
    vkuRequiredEn: 'Prerequisite: Cat B held; Medical check Level 2',
    descDe: 'Umfassende Prüfung für schwere Lastkraftwagen. 40 Fragen in 60 Minuten, max. 4 Fehler. Umfasst Druckluftbremsanlagen, Fahrphysik, EG-Kontrollgerät und Chauffeurzulassungsverordnung (CZV).',
    descEn: 'Comprehensive exam for heavy commercial trucks. 40 questions in 60 minutes, max 4 errors. Covers pneumatic brake circuits, vehicle dynamics, digital tachographs and CZV regulations.'
  },
  {
    code: 'D1',
    displayCode: 'D1',
    icon: '🚐',
    nameDe: 'Kleinbusse',
    nameFr: 'Minibus',
    nameIt: 'Minibus',
    nameEn: 'Minibuses',
    subtitleDe: 'Motorwagen mit mehr als 8 und max. 16 Sitzplätzen (ausser Fahrer)',
    subtitleFr: 'Véhicules avec plus de 8 et max. 16 places assises',
    subtitleIt: 'Veicoli con più di 8 e massimo 16 posti',
    subtitleEn: 'Passenger vehicles with 9 to 16 seats',
    minAge: 21,
    questionCount: 30,
    durationMinutes: 45,
    maxErrorPoints: 3,
    maxScore: 30,
    passRate: '90%',
    questionTypeDe: 'Single-Choice',
    questionTypeEn: 'Single-Choice',
    examTypeDe: 'Zusatztheorie C1/D1',
    examTypeEn: 'Additional Theory C1/D1',
    legalBasis: 'VZV Art. 3 Abs. 2',
    validityMonths: 24,
    vkuRequiredDe: 'Voraussetzung: Vorbesitz Kat. B seit mind. 1 Jahr',
    vkuRequiredEn: 'Prerequisite: Cat B held for at least 1 year',
    descDe: 'Gleicher Prüfungskatalog wie Kategorie C1. Befähigt zur Beförderung von bis zu 16 Fahrgästen.',
    descEn: 'Shares the Zusatztheorie C1/D1 catalog. Qualifies drivers to carry up to 16 passengers with focus on passenger safety and emergency exits.'
  },
  {
    code: 'D',
    displayCode: 'D',
    icon: '🚌',
    nameDe: 'Gesellschaftswagen (Busse)',
    nameFr: 'Autocars',
    nameIt: 'Autobus',
    nameEn: 'Coaches & Buses',
    subtitleDe: 'Motorwagen mit mehr als 16 Sitzplätzen (ausser Fahrer)',
    subtitleFr: 'Véhicules de plus de 16 places assises',
    subtitleIt: 'Autobus con oltre 16 posti a sedere',
    subtitleEn: 'Passenger vehicles with more than 16 seats',
    minAge: 21,
    questionCount: 40,
    durationMinutes: 60,
    maxErrorPoints: 4,
    maxScore: 40,
    passRate: '90%',
    questionTypeDe: 'Single-Choice',
    questionTypeEn: 'Single-Choice',
    examTypeDe: 'Zusatztheorie C/D',
    examTypeEn: 'Additional Theory C/D',
    legalBasis: 'VZV Art. 3 Abs. 1',
    validityMonths: 24,
    vkuRequiredDe: 'Vorbesitz C oder mind. 2 Jahre B; Vertrauensarzt Stufe 2',
    vkuRequiredEn: 'Category C held or 2 years B; Medical check',
    descDe: '40 Fragen zu Chauffeurzulassung, Evakuierung, Fahrgastrechten und Brandschutz.',
    descEn: '40 questions covering passenger transport law, vehicle fire suppression, evacuation protocols, and international charter guidelines.'
  },
  {
    code: 'F',
    displayCode: 'F',
    icon: '🚜',
    nameDe: 'Motorarbeitswagen',
    nameFr: 'Chariots de travail',
    nameIt: 'Veicoli di lavoro',
    nameEn: 'Special Work Vehicles',
    subtitleDe: 'Arbeitsmotorwagen bis max. 45 km/h Höchstgeschwindigkeit',
    subtitleFr: 'Chariots de travail jusqu\'à 45 km/h max',
    subtitleIt: 'Veicoli industriali fino a 45 km/h max',
    subtitleEn: 'Special work vehicles up to 45 km/h maximum speed',
    minAge: 16,
    questionCount: 40,
    durationMinutes: 45,
    maxErrorPoints: 12,
    maxScore: 120,
    passRate: '90%',
    questionTypeDe: 'Multiple-Choice',
    questionTypeEn: 'Multiple-Choice',
    examTypeDe: 'Theorieprüfung F/G',
    examTypeEn: 'Theory Exam F/G',
    legalBasis: 'VZV Art. 3 Abs. 3',
    validityMonths: 24,
    vkuRequiredDe: 'Kein VKU erforderlich',
    vkuRequiredEn: 'No VKU required',
    descDe: 'Spezifische Theorieprüfung für Arbeitsmotorfahrzeuge wie Baumaschinen, Stapler und Kommunalfahrzeuge bis 45 km/h.',
    descEn: 'Specialized theory exam for municipal vehicles, construction machinery, and industrial work vehicles up to 45 km/h.'
  },
  {
    code: 'G',
    displayCode: 'G',
    icon: '🌾',
    nameDe: 'Landwirtschaftliche Fahrzeuge',
    nameFr: 'Véhicules agricoles',
    nameIt: 'Veicoli agricoli',
    nameEn: 'Agricultural Tractors',
    subtitleDe: 'Land- und forstwirtschaftliche Motorfahrzeuge bis max. 30 km/h',
    subtitleFr: 'Véhicules agricoles et forestiers jusqu\'à 30 km/h',
    subtitleIt: 'Veicoli agricoli fino a 30 km/h',
    subtitleEn: 'Agricultural and forestry vehicles up to 30 km/h',
    minAge: 14,
    questionCount: 40,
    durationMinutes: 45,
    maxErrorPoints: 12,
    maxScore: 120,
    passRate: '90%',
    questionTypeDe: 'Multiple-Choice',
    questionTypeEn: 'Multiple-Choice',
    examTypeDe: 'Theorieprüfung F/G',
    examTypeEn: 'Theory Exam F/G',
    legalBasis: 'VZV Art. 3 Abs. 3',
    validityMonths: 24,
    vkuRequiredDe: 'Kein VKU erforderlich; G40 Ausweis ab 14 mit Kurs',
    vkuRequiredEn: 'No VKU required; G40 speed extension with certified course',
    descDe: 'Ermöglicht Jugendlichen ab 14 Jahren das Führen von Traktoren bis 30 km/h (bzw. 40 km/h mit G40-Zusatzkurs).',
    descEn: 'Enables 14-year-olds to operate agricultural tractors up to 30 km/h (or 40 km/h with the certified G40 agricultural tractor course).'
  },
  {
    code: 'M',
    displayCode: 'M',
    icon: '🛵',
    nameDe: 'Motorfahrräder (Mofas)',
    nameFr: 'Cyclomoteurs',
    nameIt: 'Ciclomotori',
    nameEn: 'Mopeds & E-Bikes',
    subtitleDe: 'Mofas und E-Bikes (schnelle E-Bikes bis 45 km/h)',
    subtitleFr: 'Cyclomoteurs et vélos électriques rapides jusqu\'à 45 km/h',
    subtitleIt: 'Ciclomotori ed e-bike veloci fino a 45 km/h',
    subtitleEn: 'Mopeds and speed pedelecs up to 45 km/h',
    minAge: 14,
    questionCount: 30,
    durationMinutes: 45,
    maxErrorPoints: 9,
    maxScore: 90,
    passRate: '90%',
    questionTypeDe: 'Multiple-Choice',
    questionTypeEn: 'Multiple-Choice',
    examTypeDe: 'Theorieprüfung M',
    examTypeEn: 'Theory Exam M',
    legalBasis: 'VZV Art. 3 Abs. 3',
    validityMonths: 24,
    vkuRequiredDe: 'Kein Nothelfer- oder VKU-Kurs erforderlich',
    vkuRequiredEn: 'No first aid or VKU required',
    descDe: 'Die Einstiegskategorie ab 14 Jahren für Mofas sowie schnelle E-Bikes (Motorunterstützung bis 45 km/h). 30 Fragen, maximal 9 Fehlerpunkte.',
    descEn: 'The beginner category starting at age 14 for mopeds and fast e-bikes (speed pedelecs up to 45 km/h). 30 questions, max 9 error points.'
  },
  {
    code: 'BPT',
    displayCode: 'BPT / 121',
    icon: '🚕',
    nameDe: 'Berufsmässiger Personentransport',
    nameFr: 'Transport professionnel de personnes',
    nameIt: 'Trasporto professionale di persone',
    nameEn: 'Professional Passenger Transport',
    subtitleDe: 'Taxi, Uber, Shuttle und Chauffeurdienste (Zusatzcode 121)',
    subtitleFr: 'Taxis, VTC, navettes et services avec chauffeur (Code 121)',
    subtitleIt: 'Taxi, Uber, navette e servizi di noleggio con conducente (Codice 121)',
    subtitleEn: 'Taxi, Uber, limousines and executive chauffeur transport (Code 121)',
    minAge: 19,
    questionCount: 30,
    durationMinutes: 45,
    maxErrorPoints: 3,
    maxScore: 30,
    passRate: '90%',
    questionTypeDe: 'Single-Choice',
    questionTypeEn: 'Single-Choice',
    examTypeDe: 'Zusatztheorie BPT (Code 121)',
    examTypeEn: 'Additional Theory BPT (Code 121)',
    legalBasis: 'VZV Art. 25; ARV 2; SVG Art. 25',
    validityMonths: 24,
    vkuRequiredDe: 'Mind. 1 Jahr Führerausweis Kat. B ohne Entzug; Vertrauensarzt Stufe 2',
    vkuRequiredEn: 'At least 1 year clean category B licence; Medical level 2',
    descDe: 'Gesetzlich vorgeschrieben für alle Fahrer im gewerblichen Personentransport (Taxi, Fahrdienstvermittler wie Uber). Behandelt ARV 2 (Fahrtenschreiber- und Pausenpflichten) und die strikte 0.10‰ Alkohol-Nulltoleranz.',
    descEn: 'Mandatory statutory credential for commercial passenger transport (Taxi, Uber, limousine). Focuses on ARV 2 tachograph and duty-period regulations and strict 0.10‰ zero alcohol tolerance.'
  }
];
