const SWISS_SIGNS_DATA = [
  {
    "code": "1.01",
    "svg": "ch_1_01.svg",
    "group": "1",
    "catDe": "Gefahrensignale",
    "catEn": "Danger Signs",
    "catFr": "Signaux de danger",
    "catIt": "Segnali di pericolo",
    "article": "Art. 4",
    "nameDe": "Rechtskurve",
    "nameEn": "Bend to the right",
    "nameFr": "Virage à droite",
    "nameIt": "Curva a destra",
    "descDe": "Warnt vor der drohenden Gefahr (Rechtskurve) und fordert erhöhte Aufmerksamkeit und Geschwindigkeitsanpassung.",
    "descEn": "Warns of an upcoming road hazard (Bend to the right) requiring reduced speed and heightened vigilance.",
    "descFr": "Avertit d'un danger potentiel (Virage à droite) et exige une attention accrue ainsi qu'une adaptation de la vitesse.",
    "descIt": "Avverte di un potenziale pericolo (Curva a destra) e richiede maggiore attenzione e riduzione della velocità."
  },
  {
    "code": "1.02",
    "svg": "ch_1_02.svg",
    "group": "1",
    "catDe": "Gefahrensignale",
    "catEn": "Danger Signs",
    "catFr": "Signaux de danger",
    "catIt": "Segnali di pericolo",
    "article": "Art. 4",
    "nameDe": "Linkskurve",
    "nameEn": "Bend to the left",
    "nameFr": "Virage à gauche",
    "nameIt": "Curva a sinistra",
    "descDe": "Warnt vor der drohenden Gefahr (Linkskurve) und fordert erhöhte Aufmerksamkeit und Geschwindigkeitsanpassung.",
    "descEn": "Warns of an upcoming road hazard (Bend to the left) requiring reduced speed and heightened vigilance.",
    "descFr": "Avertit d'un danger potentiel (Virage à gauche) et exige une attention accrue ainsi qu'une adaptation de la vitesse.",
    "descIt": "Avverte di un potenziale pericolo (Curva a sinistra) e richiede maggiore attenzione e riduzione della velocità."
  },
  {
    "code": "1.03",
    "svg": "ch_1_03.svg",
    "group": "1",
    "catDe": "Gefahrensignale",
    "catEn": "Danger Signs",
    "catFr": "Signaux de danger",
    "catIt": "Segnali di pericolo",
    "article": "Art. 4",
    "nameDe": "Doppelkurve nach rechts beginnend",
    "nameEn": "Double bend, first to the right",
    "nameFr": "Double virage, le premier à droite",
    "nameIt": "Doppia curva, la prima a destra",
    "descDe": "Warnt vor der drohenden Gefahr (Doppelkurve nach rechts beginnend) und fordert erhöhte Aufmerksamkeit und Geschwindigkeitsanpassung.",
    "descEn": "Warns of an upcoming road hazard (Double bend, first to the right) requiring reduced speed and heightened vigilance.",
    "descFr": "Avertit d'un danger potentiel (Double virage, le premier à droite) et exige une attention accrue ainsi qu'une adaptation de la vitesse.",
    "descIt": "Avverte di un potenziale pericolo (Doppia curva, la prima a destra) e richiede maggiore attenzione e riduzione della velocità."
  },
  {
    "code": "1.04",
    "svg": "ch_1_04.svg",
    "group": "1",
    "catDe": "Gefahrensignale",
    "catEn": "Danger Signs",
    "catFr": "Signaux de danger",
    "catIt": "Segnali di pericolo",
    "article": "Art. 4",
    "nameDe": "Doppelkurve nach links beginnend",
    "nameEn": "Double bend, first to the left",
    "nameFr": "Double virage, le premier à gauche",
    "nameIt": "Doppia curva, la prima a sinistra",
    "descDe": "Warnt vor der drohenden Gefahr (Doppelkurve nach links beginnend) und fordert erhöhte Aufmerksamkeit und Geschwindigkeitsanpassung.",
    "descEn": "Warns of an upcoming road hazard (Double bend, first to the left) requiring reduced speed and heightened vigilance.",
    "descFr": "Avertit d'un danger potentiel (Double virage, le premier à gauche) et exige une attention accrue ainsi qu'une adaptation de la vitesse.",
    "descIt": "Avverte di un potenziale pericolo (Doppia curva, la prima a sinistra) e richiede maggiore attenzione e riduzione della velocità."
  },
  {
    "code": "1.05",
    "svg": "ch_1_05.svg",
    "group": "1",
    "catDe": "Gefahrensignale",
    "catEn": "Danger Signs",
    "catFr": "Signaux de danger",
    "catIt": "Segnali di pericolo",
    "article": "Art. 5",
    "nameDe": "Schleudergefahr",
    "nameEn": "Slippery road",
    "nameFr": "Chaussée glissante",
    "nameIt": "Strada sdrucciolevole",
    "descDe": "Warnt vor der drohenden Gefahr (Schleudergefahr) und fordert erhöhte Aufmerksamkeit und Geschwindigkeitsanpassung.",
    "descEn": "Warns of an upcoming road hazard (Slippery road) requiring reduced speed and heightened vigilance.",
    "descFr": "Avertit d'un danger potentiel (Chaussée glissante) et exige une attention accrue ainsi qu'une adaptation de la vitesse.",
    "descIt": "Avverte di un potenziale pericolo (Strada sdrucciolevole) e richiede maggiore attenzione e riduzione della velocità."
  },
  {
    "code": "1.06",
    "svg": "ch_1_06.svg",
    "group": "1",
    "catDe": "Gefahrensignale",
    "catEn": "Danger Signs",
    "catFr": "Signaux de danger",
    "catIt": "Segnali di pericolo",
    "article": "Art. 6",
    "nameDe": "Unebene Fahrbahn",
    "nameEn": "Uneven road",
    "nameFr": "Cassis",
    "nameIt": "Cunetta",
    "descDe": "Warnt vor der drohenden Gefahr (Unebene Fahrbahn) und fordert erhöhte Aufmerksamkeit und Geschwindigkeitsanpassung.",
    "descEn": "Warns of an upcoming road hazard (Uneven road) requiring reduced speed and heightened vigilance.",
    "descFr": "Avertit d'un danger potentiel (Cassis) et exige une attention accrue ainsi qu'une adaptation de la vitesse.",
    "descIt": "Avverte di un potenziale pericolo (Cunetta) e richiede maggiore attenzione e riduzione della velocità."
  },
  {
    "code": "1.07",
    "svg": "ch_1_07.svg",
    "group": "1",
    "catDe": "Gefahrensignale",
    "catEn": "Danger Signs",
    "catFr": "Signaux de danger",
    "catIt": "Segnali di pericolo",
    "article": "Art. 7",
    "nameDe": "Engpass",
    "nameEn": "Road narrows on both sides",
    "nameFr": "Chaussée rétrécie",
    "nameIt": "Strada stretta",
    "descDe": "Warnt vor der drohenden Gefahr (Engpass) und fordert erhöhte Aufmerksamkeit und Geschwindigkeitsanpassung.",
    "descEn": "Warns of an upcoming road hazard (Road narrows on both sides) requiring reduced speed and heightened vigilance.",
    "descFr": "Avertit d'un danger potentiel (Chaussée rétrécie) et exige une attention accrue ainsi qu'une adaptation de la vitesse.",
    "descIt": "Avverte di un potenziale pericolo (Strada stretta) e richiede maggiore attenzione e riduzione della velocità."
  },
  {
    "code": "1.08",
    "svg": "ch_1_08.svg",
    "group": "1",
    "catDe": "Gefahrensignale",
    "catEn": "Danger Signs",
    "catFr": "Signaux de danger",
    "catIt": "Segnali di pericolo",
    "article": "Art. 7",
    "nameDe": "Verengung rechts",
    "nameEn": "Road narrows on the right",
    "nameFr": "Chaussée rétrécie à droite",
    "nameIt": "Restringimento a destra",
    "descDe": "Warnt vor der drohenden Gefahr (Verengung rechts) und fordert erhöhte Aufmerksamkeit und Geschwindigkeitsanpassung.",
    "descEn": "Warns of an upcoming road hazard (Road narrows on the right) requiring reduced speed and heightened vigilance.",
    "descFr": "Avertit d'un danger potentiel (Chaussée rétrécie à droite) et exige une attention accrue ainsi qu'une adaptation de la vitesse.",
    "descIt": "Avverte di un potenziale pericolo (Restringimento a destra) e richiede maggiore attenzione e riduzione della velocità."
  },
  {
    "code": "1.09",
    "svg": "ch_1_09.svg",
    "group": "1",
    "catDe": "Gefahrensignale",
    "catEn": "Danger Signs",
    "catFr": "Signaux de danger",
    "catIt": "Segnali di pericolo",
    "article": "Art. 7",
    "nameDe": "Verengung links",
    "nameEn": "Road narrows on the left",
    "nameFr": "Chaussée rétrécie à gauche",
    "nameIt": "Restringimento a sinistra",
    "descDe": "Warnt vor der drohenden Gefahr (Verengung links) und fordert erhöhte Aufmerksamkeit und Geschwindigkeitsanpassung.",
    "descEn": "Warns of an upcoming road hazard (Road narrows on the left) requiring reduced speed and heightened vigilance.",
    "descFr": "Avertit d'un danger potentiel (Chaussée rétrécie à gauche) et exige une attention accrue ainsi qu'une adaptation de la vitesse.",
    "descIt": "Avverte di un potenziale pericolo (Restringimento a sinistra) e richiede maggiore attenzione e riduzione della velocità."
  },
  {
    "code": "1.10",
    "svg": "ch_1_10.svg",
    "group": "1",
    "catDe": "Gefahrensignale",
    "catEn": "Danger Signs",
    "catFr": "Signaux de danger",
    "catIt": "Segnali di pericolo",
    "article": "Art. 8",
    "nameDe": "Gefährliches Gefälle",
    "nameEn": "Dangerous descent",
    "nameFr": "Descente dangereuse",
    "nameIt": "Discesa pericolosa",
    "descDe": "Warnt vor der drohenden Gefahr (Gefährliches Gefälle) und fordert erhöhte Aufmerksamkeit und Geschwindigkeitsanpassung.",
    "descEn": "Warns of an upcoming road hazard (Dangerous descent) requiring reduced speed and heightened vigilance.",
    "descFr": "Avertit d'un danger potentiel (Descente dangereuse) et exige une attention accrue ainsi qu'une adaptation de la vitesse.",
    "descIt": "Avverte di un potenziale pericolo (Discesa pericolosa) e richiede maggiore attenzione e riduzione della velocità."
  },
  {
    "code": "1.11",
    "svg": "ch_1_11.svg",
    "group": "1",
    "catDe": "Gefahrensignale",
    "catEn": "Danger Signs",
    "catFr": "Signaux de danger",
    "catIt": "Segnali di pericolo",
    "article": "Art. 8",
    "nameDe": "Starke Steigung",
    "nameEn": "Steep hill upwards",
    "nameFr": "Forte montée",
    "nameIt": "Salita ripida",
    "descDe": "Warnt vor der drohenden Gefahr (Starke Steigung) und fordert erhöhte Aufmerksamkeit und Geschwindigkeitsanpassung.",
    "descEn": "Warns of an upcoming road hazard (Steep hill upwards) requiring reduced speed and heightened vigilance.",
    "descFr": "Avertit d'un danger potentiel (Forte montée) et exige une attention accrue ainsi qu'une adaptation de la vitesse.",
    "descIt": "Avverte di un potenziale pericolo (Salita ripida) e richiede maggiore attenzione e riduzione della velocità."
  },
  {
    "code": "1.12",
    "svg": "ch_1_12.svg",
    "group": "1",
    "catDe": "Gefahrensignale",
    "catEn": "Danger Signs",
    "catFr": "Signaux de danger",
    "catIt": "Segnali di pericolo",
    "article": "Art. 8",
    "nameDe": "Rollsplit",
    "nameEn": "Loose chippings",
    "nameFr": "Gravillon",
    "nameIt": "Ghiaia",
    "descDe": "Warnt vor der drohenden Gefahr (Rollsplit) und fordert erhöhte Aufmerksamkeit und Geschwindigkeitsanpassung.",
    "descEn": "Warns of an upcoming road hazard (Loose chippings) requiring reduced speed and heightened vigilance.",
    "descFr": "Avertit d'un danger potentiel (Gravillon) et exige une attention accrue ainsi qu'une adaptation de la vitesse.",
    "descIt": "Avverte di un potenziale pericolo (Ghiaia) e richiede maggiore attenzione e riduzione della velocità."
  },
  {
    "code": "1.13",
    "svg": "ch_1_13.svg",
    "group": "1",
    "catDe": "Gefahrensignale",
    "catEn": "Danger Signs",
    "catFr": "Signaux de danger",
    "catIt": "Segnali di pericolo",
    "article": "Art. 8",
    "nameDe": "Steinschlag",
    "nameEn": "Falling rocks",
    "nameFr": "Chute de pierres",
    "nameIt": "Caduta di sassi",
    "descDe": "Warnt vor der drohenden Gefahr (Steinschlag) und fordert erhöhte Aufmerksamkeit und Geschwindigkeitsanpassung.",
    "descEn": "Warns of an upcoming road hazard (Falling rocks) requiring reduced speed and heightened vigilance.",
    "descFr": "Avertit d'un danger potentiel (Chute de pierres) et exige une attention accrue ainsi qu'une adaptation de la vitesse.",
    "descIt": "Avverte di un potenziale pericolo (Caduta di sassi) e richiede maggiore attenzione e riduzione della velocità."
  },
  {
    "code": "1.14",
    "svg": "ch_1_14.svg",
    "group": "1",
    "catDe": "Gefahrensignale",
    "catEn": "Danger Signs",
    "catFr": "Signaux de danger",
    "catIt": "Segnali di pericolo",
    "article": "Art. 9",
    "nameDe": "Baustelle",
    "nameEn": "Pedestrian crossing ahead",
    "nameFr": "Travaux",
    "nameIt": "Lavori",
    "descDe": "Warnt vor der drohenden Gefahr (Baustelle) und fordert erhöhte Aufmerksamkeit und Geschwindigkeitsanpassung.",
    "descEn": "Warns of an upcoming road hazard (Pedestrian crossing ahead) requiring reduced speed and heightened vigilance.",
    "descFr": "Avertit d'un danger potentiel (Travaux) et exige une attention accrue ainsi qu'une adaptation de la vitesse.",
    "descIt": "Avverte di un potenziale pericolo (Lavori) e richiede maggiore attenzione e riduzione della velocità."
  },
  {
    "code": "1.15",
    "svg": "ch_1_15.svg",
    "group": "1",
    "catDe": "Gefahrensignale",
    "catEn": "Danger Signs",
    "catFr": "Signaux de danger",
    "catIt": "Segnali di pericolo",
    "article": "Art. 10",
    "nameDe": "Schranken",
    "nameEn": "Children crossing",
    "nameFr": "Barrières",
    "nameIt": "Barriere",
    "descDe": "Warnt vor der drohenden Gefahr (Schranken) und fordert erhöhte Aufmerksamkeit und Geschwindigkeitsanpassung.",
    "descEn": "Warns of an upcoming road hazard (Children crossing) requiring reduced speed and heightened vigilance.",
    "descFr": "Avertit d'un danger potentiel (Barrières) et exige une attention accrue ainsi qu'une adaptation de la vitesse.",
    "descIt": "Avverte di un potenziale pericolo (Barriere) e richiede maggiore attenzione e riduzione della velocità."
  },
  {
    "code": "1.16",
    "svg": "ch_1_16.svg",
    "group": "1",
    "catDe": "Gefahrensignale",
    "catEn": "Danger Signs",
    "catFr": "Signaux de danger",
    "catIt": "Segnali di pericolo",
    "article": "Art. 10",
    "nameDe": "Bahnübergang ohne Schranken",
    "nameEn": "Road works",
    "nameFr": "Passage à niveau sans barrières",
    "nameIt": "Passaggio a livello senza barriere",
    "descDe": "Warnt vor der drohenden Gefahr (Bahnübergang ohne Schranken) und fordert erhöhte Aufmerksamkeit und Geschwindigkeitsanpassung.",
    "descEn": "Warns of an upcoming road hazard (Road works) requiring reduced speed and heightened vigilance.",
    "descFr": "Avertit d'un danger potentiel (Passage à niveau sans barrières) et exige une attention accrue ainsi qu'une adaptation de la vitesse.",
    "descIt": "Avverte di un potenziale pericolo (Passaggio a livello senza barriere) e richiede maggiore attenzione e riduzione della velocità."
  },
  {
    "code": "1.25",
    "svg": "ch_1_25.svg",
    "group": "1",
    "catDe": "Gefahrensignale",
    "catEn": "Danger Signs",
    "catFr": "Signaux de danger",
    "catIt": "Segnali di pericolo",
    "article": "Art. 12",
    "nameDe": "Tiere",
    "nameEn": "Level crossing with barriers",
    "nameFr": "Animaux",
    "nameIt": "Animali",
    "descDe": "Warnt vor der drohenden Gefahr (Tiere) und fordert erhöhte Aufmerksamkeit und Geschwindigkeitsanpassung.",
    "descEn": "Warns of an upcoming road hazard (Level crossing with barriers) requiring reduced speed and heightened vigilance.",
    "descFr": "Avertit d'un danger potentiel (Animaux) et exige une attention accrue ainsi qu'une adaptation de la vitesse.",
    "descIt": "Avverte di un potenziale pericolo (Animali) e richiede maggiore attenzione e riduzione della velocità."
  },
  {
    "code": "1.26",
    "svg": "ch_1_26.svg",
    "group": "1",
    "catDe": "Gefahrensignale",
    "catEn": "Danger Signs",
    "catFr": "Signaux de danger",
    "catIt": "Segnali di pericolo",
    "article": "Art. 13",
    "nameDe": "Gegenverkehr",
    "nameEn": "Level crossing without barriers",
    "nameFr": "Circulation en sens inverse",
    "nameIt": "Traffico in senso inverso",
    "descDe": "Warnt vor der drohenden Gefahr (Gegenverkehr) und fordert erhöhte Aufmerksamkeit und Geschwindigkeitsanpassung.",
    "descEn": "Warns of an upcoming road hazard (Level crossing without barriers) requiring reduced speed and heightened vigilance.",
    "descFr": "Avertit d'un danger potentiel (Circulation en sens inverse) et exige une attention accrue ainsi qu'une adaptation de la vitesse.",
    "descIt": "Avverte di un potenziale pericolo (Traffico in senso inverso) e richiede maggiore attenzione e riduzione della velocità."
  },
  {
    "code": "1.30",
    "svg": "ch_1_30.svg",
    "group": "1",
    "catDe": "Gefahrensignale",
    "catEn": "Danger Signs",
    "catFr": "Signaux de danger",
    "catIt": "Segnali di pericolo",
    "article": "Art. 15",
    "nameDe": "Andere Gefahren",
    "nameEn": "Other dangers",
    "nameFr": "Autres dangers",
    "nameIt": "Altri pericoli",
    "descDe": "Warnt vor der drohenden Gefahr (Andere Gefahren) und fordert erhöhte Aufmerksamkeit und Geschwindigkeitsanpassung.",
    "descEn": "Warns of an upcoming road hazard (Other dangers) requiring reduced speed and heightened vigilance.",
    "descFr": "Avertit d'un danger potentiel (Autres dangers) et exige une attention accrue ainsi qu'une adaptation de la vitesse.",
    "descIt": "Avverte di un potenziale pericolo (Altri pericoli) e richiede maggiore attenzione e riduzione della velocità."
  },
  {
    "code": "2.01",
    "svg": "ch_2_01.svg",
    "group": "2",
    "catDe": "Vorschriftssignale",
    "catEn": "Regulatory Signs",
    "catFr": "Signaux de prescription",
    "catIt": "Segnali di prescrizione",
    "article": "Art. 18",
    "nameDe": "Allgemeines Fahrverbot in beiden Richtungen",
    "nameEn": "No vehicles in either direction",
    "nameFr": "Interdiction générale de circuler dans les deux sens",
    "nameIt": "Divieto generale dicircolazione nelle duedirezioni",
    "descDe": "Statuiert eine verbindliche Verkehrsvorschrift (Allgemeines Fahrverbot in beiden Richtungen), die strikt eingehalten werden muss.",
    "descEn": "Enforces a mandatory traffic prohibition or restriction (No vehicles in either direction).",
    "descFr": "Établit une prescription de circulation obligatoire (Interdiction générale de circuler dans les deux sens) qui doit être scrupuleusement respectée.",
    "descIt": "Stabilisce una prescrizione vincolante (Divieto generale dicircolazione nelle duedirezioni) che deve essere rigorosamente rispettata."
  },
  {
    "code": "2.02",
    "svg": "ch_2_02.svg",
    "group": "2",
    "catDe": "Vorschriftssignale",
    "catEn": "Regulatory Signs",
    "catFr": "Signaux de prescription",
    "catIt": "Segnali di prescrizione",
    "article": "Art. 18",
    "nameDe": "Einfahrt verboten",
    "nameEn": "No entry for all vehicles",
    "nameFr": "Accès interdit",
    "nameIt": "Divieto di accesso",
    "descDe": "Statuiert eine verbindliche Verkehrsvorschrift (Einfahrt verboten), die strikt eingehalten werden muss.",
    "descEn": "Enforces a mandatory traffic prohibition or restriction (No entry for all vehicles).",
    "descFr": "Établit une prescription de circulation obligatoire (Accès interdit) qui doit être scrupuleusement respectée.",
    "descIt": "Stabilisce una prescrizione vincolante (Divieto di accesso) che deve essere rigorosamente rispettata."
  },
  {
    "code": "2.03",
    "svg": "ch_2_03.svg",
    "group": "2",
    "catDe": "Vorschriftssignale",
    "catEn": "Regulatory Signs",
    "catFr": "Signaux de prescription",
    "catIt": "Segnali di prescrizione",
    "article": "Art. 19",
    "nameDe": "Verbotfür Motorwagen",
    "nameEn": "No motor vehicles (except motorcycles)",
    "nameFr": "Circulation interdite aux voitures automobiles",
    "nameIt": "Divieto di circo-lazione per gliautoveicoli",
    "descDe": "Statuiert eine verbindliche Verkehrsvorschrift (Verbotfür Motorwagen), die strikt eingehalten werden muss.",
    "descEn": "Enforces a mandatory traffic prohibition or restriction (No motor vehicles (except motorcycles)).",
    "descFr": "Établit une prescription de circulation obligatoire (Circulation interdite aux voitures automobiles) qui doit être scrupuleusement respectée.",
    "descIt": "Stabilisce una prescrizione vincolante (Divieto di circo-lazione per gliautoveicoli) che deve essere rigorosamente rispettata."
  },
  {
    "code": "2.04",
    "svg": "ch_2_04.svg",
    "group": "2",
    "catDe": "Vorschriftssignale",
    "catEn": "Regulatory Signs",
    "catFr": "Signaux de prescription",
    "catIt": "Segnali di prescrizione",
    "article": "Art. 19",
    "nameDe": "Verbot für Motorräder",
    "nameEn": "No motorcycles",
    "nameFr": "Circulation interdite aux motocycles",
    "nameIt": "Divieto di circolazione per i motoveicoli",
    "descDe": "Statuiert eine verbindliche Verkehrsvorschrift (Verbot für Motorräder), die strikt eingehalten werden muss.",
    "descEn": "Enforces a mandatory traffic prohibition or restriction (No motorcycles).",
    "descFr": "Établit une prescription de circulation obligatoire (Circulation interdite aux motocycles) qui doit être scrupuleusement respectée.",
    "descIt": "Stabilisce una prescrizione vincolante (Divieto di circolazione per i motoveicoli) che deve essere rigorosamente rispettata."
  },
  {
    "code": "2.05",
    "svg": "ch_2_05.svg",
    "group": "2",
    "catDe": "Vorschriftssignale",
    "catEn": "Regulatory Signs",
    "catFr": "Signaux de prescription",
    "catIt": "Segnali di prescrizione",
    "article": "Art. 19",
    "nameDe": "Verbot für Fahrräderund Motorfahrräder",
    "nameEn": "No bicycles and mopeds",
    "nameFr": "Circulation interdite aux cycles et cyclomoteurs",
    "nameIt": "Divieto di circolazione per i velocipedi e i ciclomotori",
    "descDe": "Statuiert eine verbindliche Verkehrsvorschrift (Verbot für Fahrräderund Motorfahrräder), die strikt eingehalten werden muss.",
    "descEn": "Enforces a mandatory traffic prohibition or restriction (No bicycles and mopeds).",
    "descFr": "Établit une prescription de circulation obligatoire (Circulation interdite aux cycles et cyclomoteurs) qui doit être scrupuleusement respectée.",
    "descIt": "Stabilisce una prescrizione vincolante (Divieto di circolazione per i velocipedi e i ciclomotori) che deve essere rigorosamente rispettata."
  },
  {
    "code": "2.06",
    "svg": "ch_2_06.svg",
    "group": "2",
    "catDe": "Vorschriftssignale",
    "catEn": "Regulatory Signs",
    "catFr": "Signaux de prescription",
    "catIt": "Segnali di prescrizione",
    "article": "Art. 19",
    "nameDe": "Verbot für Motorfahrräder",
    "nameEn": "No mopeds",
    "nameFr": "Circulation interdite aux cyclomoteurs",
    "nameIt": "Divieto di circolazione per i ciclo-motori",
    "descDe": "Statuiert eine verbindliche Verkehrsvorschrift (Verbot für Motorfahrräder), die strikt eingehalten werden muss.",
    "descEn": "Enforces a mandatory traffic prohibition or restriction (No mopeds).",
    "descFr": "Établit une prescription de circulation obligatoire (Circulation interdite aux cyclomoteurs) qui doit être scrupuleusement respectée.",
    "descIt": "Stabilisce una prescrizione vincolante (Divieto di circolazione per i ciclo-motori) che deve essere rigorosamente rispettata."
  },
  {
    "code": "2.07",
    "svg": "ch_2_07.svg",
    "group": "2",
    "catDe": "Vorschriftssignale",
    "catEn": "Regulatory Signs",
    "catFr": "Signaux de prescription",
    "catIt": "Segnali di prescrizione",
    "article": "Art. 19",
    "nameDe": "Verbot für Lastwagen",
    "nameEn": "No heavy goods vehicles (trucks)",
    "nameFr": "Circulation interdite aux camions",
    "nameIt": "Divieto di circolazione per gli autocarri",
    "descDe": "Statuiert eine verbindliche Verkehrsvorschrift (Verbot für Lastwagen), die strikt eingehalten werden muss.",
    "descEn": "Enforces a mandatory traffic prohibition or restriction (No heavy goods vehicles (trucks)).",
    "descFr": "Établit une prescription de circulation obligatoire (Circulation interdite aux camions) qui doit être scrupuleusement respectée.",
    "descIt": "Stabilisce una prescrizione vincolante (Divieto di circolazione per gli autocarri) che deve essere rigorosamente rispettata."
  },
  {
    "code": "2.08",
    "svg": "ch_2_08.svg",
    "group": "2",
    "catDe": "Vorschriftssignale",
    "catEn": "Regulatory Signs",
    "catFr": "Signaux de prescription",
    "catIt": "Segnali di prescrizione",
    "article": "Art. 19",
    "nameDe": "Verbot für Gesellschaftswagen",
    "nameEn": "No buses / coaches",
    "nameFr": "Circulation interdite aux autocars",
    "nameIt": "Divieto di circolazione per gli autobus",
    "descDe": "Statuiert eine verbindliche Verkehrsvorschrift (Verbot für Gesellschaftswagen), die strikt eingehalten werden muss.",
    "descEn": "Enforces a mandatory traffic prohibition or restriction (No buses / coaches).",
    "descFr": "Établit une prescription de circulation obligatoire (Circulation interdite aux autocars) qui doit être scrupuleusement respectée.",
    "descIt": "Stabilisce una prescrizione vincolante (Divieto di circolazione per gli autobus) che deve essere rigorosamente rispettata."
  },
  {
    "code": "2.09",
    "svg": "ch_2_09.svg",
    "group": "2",
    "catDe": "Vorschriftssignale",
    "catEn": "Regulatory Signs",
    "catFr": "Signaux de prescription",
    "catIt": "Segnali di prescrizione",
    "article": "Art. 19",
    "nameDe": "Verbot für Anhänger",
    "nameEn": "No trailers",
    "nameFr": "Circulation interdite aux remorques",
    "nameIt": "Divieto di circolazione per i rimorchi",
    "descDe": "Statuiert eine verbindliche Verkehrsvorschrift (Verbot für Anhänger), die strikt eingehalten werden muss.",
    "descEn": "Enforces a mandatory traffic prohibition or restriction (No trailers).",
    "descFr": "Établit une prescription de circulation obligatoire (Circulation interdite aux remorques) qui doit être scrupuleusement respectée.",
    "descIt": "Stabilisce una prescrizione vincolante (Divieto di circolazione per i rimorchi) che deve essere rigorosamente rispettata."
  },
  {
    "code": "2.11",
    "svg": "ch_2_11.svg",
    "group": "2",
    "catDe": "Vorschriftssignale",
    "catEn": "Regulatory Signs",
    "catFr": "Signaux de prescription",
    "catIt": "Segnali di prescrizione",
    "article": "Art. 19",
    "nameDe": "Verbot für Fahrzeuge mit wassergefährdender Ladung",
    "nameEn": "No vehicles carrying water pollutants",
    "nameFr": "Circulation interdite aux véhicules dont le chargement peut altérer les eaux",
    "nameIt": "Divieto di circolazione per i veicoli il cui carico può inquinare le acque",
    "descDe": "Statuiert eine verbindliche Verkehrsvorschrift (Verbot für Fahrzeuge mit wassergefährdender Ladung), die strikt eingehalten werden muss.",
    "descEn": "Enforces a mandatory traffic prohibition or restriction (No vehicles carrying water pollutants).",
    "descFr": "Établit une prescription de circulation obligatoire (Circulation interdite aux véhicules dont le chargement peut altérer les eaux) qui doit être scrupuleusement respectée.",
    "descIt": "Stabilisce una prescrizione vincolante (Divieto di circolazione per i veicoli il cui carico può inquinare le acque) che deve essere rigorosamente rispettata."
  },
  {
    "code": "2.13",
    "svg": "ch_2_13.svg",
    "group": "2",
    "catDe": "Vorschriftssignale",
    "catEn": "Regulatory Signs",
    "catFr": "Signaux de prescription",
    "catIt": "Segnali di prescrizione",
    "article": "Art. 19",
    "nameDe": "Verbot für Motorwagen und Motorräder",
    "nameEn": "No motor vehicles or motorcycles",
    "nameFr": "Circulation interdite aux voitures automobiles et aux motocycles",
    "nameIt": "Divieto di circolazione per gli autoveicoli e i motoveicoli",
    "descDe": "Statuiert eine verbindliche Verkehrsvorschrift (Verbot für Motorwagen und Motorräder), die strikt eingehalten werden muss.",
    "descEn": "Enforces a mandatory traffic prohibition or restriction (No motor vehicles or motorcycles).",
    "descFr": "Établit une prescription de circulation obligatoire (Circulation interdite aux voitures automobiles et aux motocycles) qui doit être scrupuleusement respectée.",
    "descIt": "Stabilisce una prescrizione vincolante (Divieto di circolazione per gli autoveicoli e i motoveicoli) che deve essere rigorosamente rispettata."
  },
  {
    "code": "2.14",
    "svg": "ch_2_14.svg",
    "group": "2",
    "catDe": "Vorschriftssignale",
    "catEn": "Regulatory Signs",
    "catFr": "Signaux de prescription",
    "catIt": "Segnali di prescrizione",
    "article": "Art. 19",
    "nameDe": "Verbot für Motorwagen, Motorräder und Motorfahrräder",
    "nameEn": "No motor vehicles, motorcycles, or mopeds",
    "nameFr": "Circulation interdite aux voitures automobiles, aux motocycles et cyclomoteurs",
    "nameIt": "Divieto di circolazione per gli autoveicoli i motoveicoli e i ciclomotori",
    "descDe": "Verbietet die Einfahrt und Weiterfahrt für alle mehrspurigen Motorfahrzeuge, Motorräder sowie Kleinmotorräder und Motorfahrräder.",
    "descEn": "Prohibits entry and thoroughfare for all motor vehicles, motorcycles, and mopeds.",
    "descFr": "Interdit l'accès et la circulation à tous les véhicules automobiles, motocycles et cyclomoteurs.",
    "descIt": "Vieta l'accesso e la circolazione a tutti gli autoveicoli, motoveicoli e ciclomotori."
  },
  {
    "code": "2.15",
    "svg": "ch_2_15.svg",
    "group": "2",
    "catDe": "Vorschriftssignale",
    "catEn": "Regulatory Signs",
    "catFr": "Signaux de prescription",
    "catIt": "Segnali di prescrizione",
    "article": "Art. 19",
    "nameDe": "Verbot für Fussgänger",
    "nameEn": "No pedestrians",
    "nameFr": "Accès interditaux piétons",
    "nameIt": "Accesso vietato aipedoni",
    "descDe": "Statuiert eine verbindliche Verkehrsvorschrift (Verbot für Fussgänger), die strikt eingehalten werden muss.",
    "descEn": "Enforces a mandatory traffic prohibition or restriction (No pedestrians).",
    "descFr": "Établit une prescription de circulation obligatoire (Accès interditaux piétons) qui doit être scrupuleusement respectée.",
    "descIt": "Stabilisce una prescrizione vincolante (Accesso vietato aipedoni) che deve essere rigorosamente rispettata."
  },
  {
    "code": "2.16",
    "svg": "ch_2_16.svg",
    "group": "2",
    "catDe": "Vorschriftssignale",
    "catEn": "Regulatory Signs",
    "catFr": "Signaux de prescription",
    "catIt": "Segnali di prescrizione",
    "article": "Art. 20",
    "nameDe": "Höchstgewicht",
    "nameEn": "Maximum gross weight",
    "nameFr": "Poids maximal",
    "nameIt": "Peso massimo",
    "descDe": "Schliesst Fahrzeuge und Fahrzeugkombinationen aus, deren tatsächliches Betriebsgewicht den angegebenen Wert übersteigt.",
    "descEn": "Excludes vehicles and vehicle combinations whose actual operating gross weight exceeds the specified value.",
    "descFr": "Exclut les véhicules et ensembles dont le poids effectif dépasse la valeur indiquée.",
    "descIt": "Esclude i veicoli e i complessi il cui peso effettivo supera il valore indicato."
  },
  {
    "code": "2.17",
    "svg": "ch_2_17.svg",
    "group": "2",
    "catDe": "Vorschriftssignale",
    "catEn": "Regulatory Signs",
    "catFr": "Signaux de prescription",
    "catIt": "Segnali di prescrizione",
    "article": "Art. 20",
    "nameDe": "Achsdruck",
    "nameEn": "Maximum axle load",
    "nameFr": "Charge par essieu",
    "nameIt": "Pressione sull’asse",
    "descDe": "Statuiert eine verbindliche Verkehrsvorschrift (Achsdruck), die strikt eingehalten werden muss.",
    "descEn": "Enforces a mandatory traffic prohibition or restriction (Maximum axle load).",
    "descFr": "Établit une prescription de circulation obligatoire (Charge par essieu) qui doit être scrupuleusement respectée.",
    "descIt": "Stabilisce una prescrizione vincolante (Pressione sull’asse) che deve essere rigorosamente rispettata."
  },
  {
    "code": "2.18",
    "svg": "ch_2_18.svg",
    "group": "2",
    "catDe": "Vorschriftssignale",
    "catEn": "Regulatory Signs",
    "catFr": "Signaux de prescription",
    "catIt": "Segnali di prescrizione",
    "article": "Art. 21",
    "nameDe": "Höchstbreite",
    "nameEn": "Maximum vehicle width",
    "nameFr": "Largeur maximale",
    "nameIt": "Larghezza massima",
    "descDe": "Statuiert eine verbindliche Verkehrsvorschrift (Höchstbreite), die strikt eingehalten werden muss.",
    "descEn": "Enforces a mandatory traffic prohibition or restriction (Maximum vehicle width).",
    "descFr": "Établit une prescription de circulation obligatoire (Largeur maximale) qui doit être scrupuleusement respectée.",
    "descIt": "Stabilisce una prescrizione vincolante (Larghezza massima) che deve essere rigorosamente rispettata."
  },
  {
    "code": "2.19",
    "svg": "ch_2_19.svg",
    "group": "2",
    "catDe": "Vorschriftssignale",
    "catEn": "Regulatory Signs",
    "catFr": "Signaux de prescription",
    "catIt": "Segnali di prescrizione",
    "article": "Art. 21",
    "nameDe": "Höchsthöhe",
    "nameEn": "Maximum vehicle height",
    "nameFr": "Hauteur maximale",
    "nameIt": "Altezza massima",
    "descDe": "Statuiert eine verbindliche Verkehrsvorschrift (Höchsthöhe), die strikt eingehalten werden muss.",
    "descEn": "Enforces a mandatory traffic prohibition or restriction (Maximum vehicle height).",
    "descFr": "Établit une prescription de circulation obligatoire (Hauteur maximale) qui doit être scrupuleusement respectée.",
    "descIt": "Stabilisce una prescrizione vincolante (Altezza massima) che deve essere rigorosamente rispettata."
  },
  {
    "code": "2.20",
    "svg": "ch_2_20.svg",
    "group": "2",
    "catDe": "Vorschriftssignale",
    "catEn": "Regulatory Signs",
    "catFr": "Signaux de prescription",
    "catIt": "Segnali di prescrizione",
    "article": "Art. 21",
    "nameDe": "Höchstlänge",
    "nameEn": "Maximum vehicle length",
    "nameFr": "Longueur maximale",
    "nameIt": "Lunghezza massima",
    "descDe": "Statuiert eine verbindliche Verkehrsvorschrift (Höchstlänge), die strikt eingehalten werden muss.",
    "descEn": "Enforces a mandatory traffic prohibition or restriction (Maximum vehicle length).",
    "descFr": "Établit une prescription de circulation obligatoire (Longueur maximale) qui doit être scrupuleusement respectée.",
    "descIt": "Stabilisce una prescrizione vincolante (Lunghezza massima) che deve essere rigorosamente rispettata."
  },
  {
    "code": "2.30",
    "svg": "ch_2_30.svg",
    "group": "2",
    "catDe": "Vorschriftssignale",
    "catEn": "Regulatory Signs",
    "catFr": "Signaux de prescription",
    "catIt": "Segnali di prescrizione",
    "article": "Art. 22",
    "nameDe": "Höchstgeschwindigkeit",
    "nameEn": "Maximum speed limit",
    "nameFr": "Vitesse maximale",
    "nameIt": "Velocità massima",
    "descDe": "Statuiert eine verbindliche Verkehrsvorschrift (Höchstgeschwindigkeit), die strikt eingehalten werden muss.",
    "descEn": "Enforces a mandatory traffic prohibition or restriction (Maximum speed limit).",
    "descFr": "Établit une prescription de circulation obligatoire (Vitesse maximale) qui doit être scrupuleusement respectée.",
    "descIt": "Stabilisce una prescrizione vincolante (Velocità massima) che deve essere rigorosamente rispettata."
  },
  {
    "code": "2.31",
    "svg": "ch_2_31.svg",
    "group": "2",
    "catDe": "Vorschriftssignale",
    "catEn": "Regulatory Signs",
    "catFr": "Signaux de prescription",
    "catIt": "Segnali di prescrizione",
    "article": "Art. 23",
    "nameDe": "Mindestgeschwin digkeit",
    "nameEn": "Minimum speed limit",
    "nameFr": "Vitesse minimale",
    "nameIt": "Velocità minima",
    "descDe": "Statuiert eine verbindliche Verkehrsvorschrift (Mindestgeschwin digkeit), die strikt eingehalten werden muss.",
    "descEn": "Enforces a mandatory traffic prohibition or restriction (Minimum speed limit).",
    "descFr": "Établit une prescription de circulation obligatoire (Vitesse minimale) qui doit être scrupuleusement respectée.",
    "descIt": "Stabilisce una prescrizione vincolante (Velocità minima) che deve essere rigorosamente rispettata."
  },
  {
    "code": "2.44",
    "svg": "ch_2_44.svg",
    "group": "2",
    "catDe": "Vorschriftssignale",
    "catEn": "Regulatory Signs",
    "catFr": "Signaux de prescription",
    "catIt": "Segnali di prescrizione",
    "article": "Art. 26",
    "nameDe": "Überholen verboten",
    "nameEn": "No overtaking",
    "nameFr": "Interdictionde dépasser",
    "nameIt": "Divieto di sorpasso",
    "descDe": "Statuiert eine verbindliche Verkehrsvorschrift (Überholen verboten), die strikt eingehalten werden muss.",
    "descEn": "Enforces a mandatory traffic prohibition or restriction (No overtaking).",
    "descFr": "Établit une prescription de circulation obligatoire (Interdictionde dépasser) qui doit être scrupuleusement respectée.",
    "descIt": "Stabilisce una prescrizione vincolante (Divieto di sorpasso) che deve essere rigorosamente rispettata."
  },
  {
    "code": "2.45",
    "svg": "ch_2_45.svg",
    "group": "2",
    "catDe": "Vorschriftssignale",
    "catEn": "Regulatory Signs",
    "catFr": "Signaux de prescription",
    "catIt": "Segnali di prescrizione",
    "article": "Art. 26",
    "nameDe": "Überholen für Lastwagen verboten",
    "nameEn": "No overtaking for heavy goods vehicles",
    "nameFr": "Interdiction auxcamions de dépasser",
    "nameIt": "Divieto di sorpasso per gli autocarri",
    "descDe": "Untersagt schweren Motorwagen zum Sachentransport (> 3.5t Gesamtgewicht) das Überholen mehrspuriger fahrender Motorfahrzeuge.",
    "descEn": "Prohibits heavy goods vehicles (> 3.5t gross weight) from overtaking moving multi-track motor vehicles.",
    "descFr": "Interdit aux camions et poids lourds (> 3.5t) de dépasser des véhicules automobiles à plusieurs roues en mouvement.",
    "descIt": "Vieta agli autocarri pesanti (> 3.5t) di sorpassare veicoli a motore a più ruote in movimento."
  },
  {
    "code": "2.46",
    "svg": "ch_2_46.svg",
    "group": "2",
    "catDe": "Vorschriftssignale",
    "catEn": "Regulatory Signs",
    "catFr": "Signaux de prescription",
    "catIt": "Segnali di prescrizione",
    "article": "Art. 27",
    "nameDe": "Wenden verboten",
    "nameEn": "No U-turns",
    "nameFr": "Interdiction de fairedemi-tour",
    "nameIt": "Divieto d’inversione",
    "descDe": "Statuiert eine verbindliche Verkehrsvorschrift (Wenden verboten), die strikt eingehalten werden muss.",
    "descEn": "Enforces a mandatory traffic prohibition or restriction (No U-turns).",
    "descFr": "Établit une prescription de circulation obligatoire (Interdiction de fairedemi-tour) qui doit être scrupuleusement respectée.",
    "descIt": "Stabilisce una prescrizione vincolante (Divieto d’inversione) che deve essere rigorosamente rispettata."
  },
  {
    "code": "2.47",
    "svg": "ch_2_47.svg",
    "group": "2",
    "catDe": "Vorschriftssignale",
    "catEn": "Regulatory Signs",
    "catFr": "Signaux de prescription",
    "catIt": "Segnali di prescrizione",
    "article": "Art. 28",
    "nameDe": "Mindestabstand",
    "nameEn": "Minimum following distance for heavy vehicles",
    "nameFr": "Distance minimale",
    "nameIt": "Intervallo minimo",
    "descDe": "Statuiert eine verbindliche Verkehrsvorschrift (Mindestabstand), die strikt eingehalten werden muss.",
    "descEn": "Enforces a mandatory traffic prohibition or restriction (Minimum following distance for heavy vehicles).",
    "descFr": "Établit une prescription de circulation obligatoire (Distance minimale) qui doit être scrupuleusement respectée.",
    "descIt": "Stabilisce una prescrizione vincolante (Intervallo minimo) che deve essere rigorosamente rispettata."
  },
  {
    "code": "2.48",
    "svg": "ch_2_48.svg",
    "group": "2",
    "catDe": "Vorschriftssignale",
    "catEn": "Regulatory Signs",
    "catFr": "Signaux de prescription",
    "catIt": "Segnali di prescrizione",
    "article": "Art. 29",
    "nameDe": "Schneeketten obligatorisch",
    "nameEn": "Snow chains mandatory",
    "nameFr": "Chaînes à neigeobligatoires",
    "nameIt": "Catene per la neve obbligatorie",
    "descDe": "Statuiert eine verbindliche Verkehrsvorschrift (Schneeketten obligatorisch), die strikt eingehalten werden muss.",
    "descEn": "Enforces a mandatory traffic prohibition or restriction (Snow chains mandatory).",
    "descFr": "Établit une prescription de circulation obligatoire (Chaînes à neigeobligatoires) qui doit être scrupuleusement respectée.",
    "descIt": "Stabilisce una prescrizione vincolante (Catene per la neve obbligatorie) che deve essere rigorosamente rispettata."
  },
  {
    "code": "2.49",
    "svg": "ch_2_49.svg",
    "group": "2",
    "catDe": "Vorschriftssignale",
    "catEn": "Regulatory Signs",
    "catFr": "Signaux de prescription",
    "catIt": "Segnali di prescrizione",
    "article": "Art. 30",
    "nameDe": "Halten verboten",
    "nameEn": "No stopping",
    "nameFr": "Interdiction de s’arrêter",
    "nameIt": "Divieto di fermata",
    "descDe": "Statuiert eine verbindliche Verkehrsvorschrift (Halten verboten), die strikt eingehalten werden muss.",
    "descEn": "Enforces a mandatory traffic prohibition or restriction (No stopping).",
    "descFr": "Établit une prescription de circulation obligatoire (Interdiction de s’arrêter) qui doit être scrupuleusement respectée.",
    "descIt": "Stabilisce una prescrizione vincolante (Divieto di fermata) che deve essere rigorosamente rispettata."
  },
  {
    "code": "2.50",
    "svg": "ch_2_50.svg",
    "group": "2",
    "catDe": "Vorschriftssignale",
    "catEn": "Regulatory Signs",
    "catFr": "Signaux de prescription",
    "catIt": "Segnali di prescrizione",
    "article": "Art. 30",
    "nameDe": "Parkieren verboten",
    "nameEn": "No parking",
    "nameFr": "Interdiction de parquer",
    "nameIt": "Divieto di parcheggio",
    "descDe": "Statuiert eine verbindliche Verkehrsvorschrift (Parkieren verboten), die strikt eingehalten werden muss.",
    "descEn": "Enforces a mandatory traffic prohibition or restriction (No parking).",
    "descFr": "Établit une prescription de circulation obligatoire (Interdiction de parquer) qui doit être scrupuleusement respectée.",
    "descIt": "Stabilisce una prescrizione vincolante (Divieto di parcheggio) che deve essere rigorosamente rispettata."
  },
  {
    "code": "3.01",
    "svg": "ch_3_01.svg",
    "group": "3",
    "catDe": "Vortrittssignale",
    "catEn": "Priority Signs",
    "catFr": "Signaux de priorité",
    "catIt": "Segnali di precedenza",
    "article": "Art. 36",
    "nameDe": "Stop",
    "nameEn": "Stop and give way",
    "nameFr": "Stop",
    "nameIt": "Stop",
    "descDe": "Verpflichtet den Führer, an der Haltelinie (oder Sichtlinie) vollständig anzuhalten und Querverkehr Vortritt zu gewähren.",
    "descEn": "Requires the driver to come to a complete stop at the stop line and yield right of way to all crossing traffic.",
    "descFr": "Oblige le conducteur à marquer un arrêt absolu à la ligne d'arrêt et à accorder la priorité.",
    "descIt": "Obbliga il conducente ad arrestarsi completamente alla linea d'arresto e a dare la precedenza."
  },
  {
    "code": "3.02",
    "svg": "ch_3_02.svg",
    "group": "3",
    "catDe": "Vortrittssignale",
    "catEn": "Priority Signs",
    "catFr": "Signaux de priorité",
    "catIt": "Segnali di precedenza",
    "article": "Art. 36",
    "nameDe": "Kein Vortritt",
    "nameEn": "Give way (Yield)",
    "nameFr": "Cédez le passage",
    "nameIt": "Dare precedenza",
    "descDe": "Entzieht den Vortritt gegenüber dem Verkehr auf der kreuzenden Strasse. Anhalten nur bei herannahendem Verkehr erforderlich.",
    "descEn": "Requires yielding right of way to cross traffic. Stopping is only mandatory if conflicting traffic approaches.",
    "descFr": "Retire la priorité par rapport au trafic de la route croisée. Arrêt obligatoire uniquement si des véhicules approchent.",
    "descIt": "Toglie la precedenza rispetto al traffico sulla strada incrociata. Fermarsi solo in presenza di altri veicoli."
  },
  {
    "code": "3.03",
    "svg": "ch_3_03.svg",
    "group": "3",
    "catDe": "Vortrittssignale",
    "catEn": "Priority Signs",
    "catFr": "Signaux de priorité",
    "catIt": "Segnali di precedenza",
    "article": "Art. 37",
    "nameDe": "Hauptstrasse",
    "nameEn": "Priority road",
    "nameFr": "Route principale",
    "nameIt": "Strada principale",
    "descDe": "Regelt die Vortrittsverhältnisse an Verzweigungen verbindlich abweichend vom allgemeinen Rechtsvortritt.",
    "descEn": "Regulates right-of-way priority at junctions, overriding the default right-hand rule.",
    "descFr": "Réglemente le droit de priorité aux intersections en dérogation à la priorité légale de droite.",
    "descIt": "Regola il diritto di precedenza agli incroci derogando alla precedenza generale da destra."
  },
  {
    "code": "3.04",
    "svg": "ch_3_04.svg",
    "group": "3",
    "catDe": "Vortrittssignale",
    "catEn": "Priority Signs",
    "catFr": "Signaux de priorité",
    "catIt": "Segnali di precedenza",
    "article": "Art. 38",
    "nameDe": "Ende der Hauptstrasse",
    "nameEn": "End of priority road",
    "nameFr": "Fin de la route principale",
    "nameIt": "Fine della stradaprincipale",
    "descDe": "Regelt die Vortrittsverhältnisse an Verzweigungen verbindlich abweichend vom allgemeinen Rechtsvortritt.",
    "descEn": "Regulates right-of-way priority at junctions, overriding the default right-hand rule.",
    "descFr": "Réglemente le droit de priorité aux intersections en dérogation à la priorité légale de droite.",
    "descIt": "Regola il diritto di precedenza agli incroci derogando alla precedenza generale da destra."
  },
  {
    "code": "3.09",
    "svg": "ch_3_09.svg",
    "group": "3",
    "catDe": "Vortrittssignale",
    "catEn": "Priority Signs",
    "catFr": "Signaux de priorité",
    "catIt": "Segnali di precedenza",
    "article": "Art. 42",
    "nameDe": "Dem Gegenverkehr Vortritt lassen",
    "nameEn": "Give priority to oncoming traffic",
    "nameFr": "Laissez passer les véhiculesen sens inverse",
    "nameIt": "Lasciar passare i veicoli provenienti in senso inverso",
    "descDe": "Regelt die Vortrittsverhältnisse an Verzweigungen verbindlich abweichend vom allgemeinen Rechtsvortritt.",
    "descEn": "Regulates right-of-way priority at junctions, overriding the default right-hand rule.",
    "descFr": "Réglemente le droit de priorité aux intersections en dérogation à la priorité légale de droite.",
    "descIt": "Regola il diritto di precedenza agli incroci derogando alla precedenza generale da destra."
  },
  {
    "code": "3.10",
    "svg": "ch_3_10.svg",
    "group": "3",
    "catDe": "Vortrittssignale",
    "catEn": "Priority Signs",
    "catFr": "Signaux de priorité",
    "catIt": "Segnali di precedenza",
    "article": "Art. 42",
    "nameDe": "Vortritt vor dem Gegenverkehr",
    "nameEn": "Priority over oncoming traffic",
    "nameFr": "Priorité par rapport aux véhicules venant en sens inverse",
    "nameIt": "Precedenza rispetto al traffico inverso",
    "descDe": "Regelt die Vortrittsverhältnisse an Verzweigungen verbindlich abweichend vom allgemeinen Rechtsvortritt.",
    "descEn": "Regulates right-of-way priority at junctions, overriding the default right-hand rule.",
    "descFr": "Réglemente le droit de priorité aux intersections en dérogation à la priorité légale de droite.",
    "descIt": "Regola il diritto di precedenza agli incroci derogando alla precedenza generale da destra."
  },
  {
    "code": "4.01",
    "svg": "ch_4_01.svg",
    "group": "4",
    "catDe": "Hinweissignale",
    "catEn": "Information Signs",
    "catFr": "Signaux d'indication",
    "catIt": "Segnali d'indicazione",
    "article": "Art. 45",
    "nameDe": "Autobahn",
    "nameEn": "Motorway (Autobahn)",
    "nameFr": "Autoroute",
    "nameIt": "Autostrada",
    "descDe": "Gibt dem Verkehrsteilnehmer wichtige Verhaltenshinweise und Orientierungshilfen (Autobahn).",
    "descEn": "Provides motorists with operational roadway guidance and navigation assistance (Motorway (Autobahn)).",
    "descFr": "Fournit aux usagers des indications utiles et des repères d'orientation (Autoroute).",
    "descIt": "Fornisce agli utenti indicazioni utili e riferimenti di orientamento (Autostrada)."
  },
  {
    "code": "4.02",
    "svg": "ch_4_02.svg",
    "group": "4",
    "catDe": "Hinweissignale",
    "catEn": "Information Signs",
    "catFr": "Signaux d'indication",
    "catIt": "Segnali d'indicazione",
    "article": "Art. 45",
    "nameDe": "Ende der Autobahn",
    "nameEn": "End of motorway",
    "nameFr": "Fin de l’autoroute",
    "nameIt": "Fine dell’autostrada",
    "descDe": "Gibt dem Verkehrsteilnehmer wichtige Verhaltenshinweise und Orientierungshilfen (Ende der Autobahn).",
    "descEn": "Provides motorists with operational roadway guidance and navigation assistance (End of motorway).",
    "descFr": "Fournit aux usagers des indications utiles et des repères d'orientation (Fin de l’autoroute).",
    "descIt": "Fornisce agli utenti indicazioni utili e riferimenti di orientamento (Fine dell’autostrada)."
  },
  {
    "code": "4.03",
    "svg": "ch_4_03.svg",
    "group": "4",
    "catDe": "Hinweissignale",
    "catEn": "Information Signs",
    "catFr": "Signaux d'indication",
    "catIt": "Segnali d'indicazione",
    "article": "Art. 45",
    "nameDe": "Autostrasse",
    "nameEn": "Expressway (Autostrasse)",
    "nameFr": "Semi-autoroute",
    "nameIt": "Semiautostrada",
    "descDe": "Gibt dem Verkehrsteilnehmer wichtige Verhaltenshinweise und Orientierungshilfen (Autostrasse).",
    "descEn": "Provides motorists with operational roadway guidance and navigation assistance (Expressway (Autostrasse)).",
    "descFr": "Fournit aux usagers des indications utiles et des repères d'orientation (Semi-autoroute).",
    "descIt": "Fornisce agli utenti indicazioni utili e riferimenti di orientamento (Semiautostrada)."
  },
  {
    "code": "4.04",
    "svg": "ch_4_04.svg",
    "group": "4",
    "catDe": "Hinweissignale",
    "catEn": "Information Signs",
    "catFr": "Signaux d'indication",
    "catIt": "Segnali d'indicazione",
    "article": "Art. 45",
    "nameDe": "Ende der Autostrasse",
    "nameEn": "End of expressway",
    "nameFr": "Fin de la semi-autoroute",
    "nameIt": "Fine della semi-autostrada",
    "descDe": "Gibt dem Verkehrsteilnehmer wichtige Verhaltenshinweise und Orientierungshilfen (Ende der Autostrasse).",
    "descEn": "Provides motorists with operational roadway guidance and navigation assistance (End of expressway).",
    "descFr": "Fournit aux usagers des indications utiles et des repères d'orientation (Fin de la semi-autoroute).",
    "descIt": "Fornisce agli utenti indicazioni utili e riferimenti di orientamento (Fine della semi-autostrada)."
  },
  {
    "code": "4.05",
    "svg": "ch_4_05.svg",
    "group": "4",
    "catDe": "Hinweissignale",
    "catEn": "Information Signs",
    "catFr": "Signaux d'indication",
    "catIt": "Segnali d'indicazione",
    "article": "SSV Art. 45",
    "nameDe": "Bergpoststrasse",
    "nameEn": "Mountain Post Road",
    "nameFr": "Route pour postes de montagne",
    "nameIt": "Strada postale di montagna",
    "descDe": "Kennzeichnet Bergpoststrassen. Auf diesen Strassen haben Postautokurse im Linienverkehr Vortritt, und Verkehrsteilnehmer müssen die Zeichen der Chauffeure beachten.",
    "descEn": "Designates mountain postal roads. Public service postal buses have priority; drivers must heed bus horn and driver signals on narrow sections.",
    "descFr": "Désigne les routes pour postes de montagne. Les autocars postaux en service régulier bénéficient de la priorité; conformez-vous aux signaux des chauffeurs.",
    "descIt": "Indica strade postali di montagna. I veicoli postali di linea hanno la precedenza; i conducenti devono seguire i segnali e le indicazioni dei conducenti postali."
  },
  {
    "code": "4.08",
    "svg": "ch_4_08.svg",
    "group": "4",
    "catDe": "Hinweissignale",
    "catEn": "Information Signs",
    "catFr": "Signaux d'indication",
    "catIt": "Segnali d'indicazione",
    "article": "Art. 46",
    "nameDe": "Einbahnstrasse",
    "nameEn": "One-way street",
    "nameFr": "Sens unique",
    "nameIt": "Senso unico",
    "descDe": "Gibt dem Verkehrsteilnehmer wichtige Verhaltenshinweise und Orientierungshilfen (Einbahnstrasse).",
    "descEn": "Provides motorists with operational roadway guidance and navigation assistance (One-way street).",
    "descFr": "Fournit aux usagers des indications utiles et des repères d'orientation (Sens unique).",
    "descIt": "Fornisce agli utenti indicazioni utili e riferimenti di orientamento (Senso unico)."
  },
  {
    "code": "4.14",
    "svg": "ch_4_14.svg",
    "group": "4",
    "catDe": "Hinweissignale",
    "catEn": "Information Signs",
    "catFr": "Signaux d'indication",
    "catIt": "Segnali d'indicazione",
    "article": "Art. 47",
    "nameDe": "Spital",
    "nameEn": "No through road (Cul-de-sac)",
    "nameFr": "Hôpital",
    "nameIt": "Ospedale",
    "descDe": "Gibt dem Verkehrsteilnehmer wichtige Verhaltenshinweise und Orientierungshilfen (Spital).",
    "descEn": "Provides motorists with operational roadway guidance and navigation assistance (No through road (Cul-de-sac)).",
    "descFr": "Fournit aux usagers des indications utiles et des repères d'orientation (Hôpital).",
    "descIt": "Fornisce agli utenti indicazioni utili e riferimenti di orientamento (Ospedale)."
  },
  {
    "code": "4.17",
    "svg": "ch_4_17.svg",
    "group": "4",
    "catDe": "Hinweissignale",
    "catEn": "Information Signs",
    "catFr": "Signaux d'indication",
    "catIt": "Segnali d'indicazione",
    "article": "Art. 48",
    "nameDe": "Parkieren gestattet",
    "nameEn": "Parking permitted",
    "nameFr": "Parcage autorisé",
    "nameIt": "Parcheggio",
    "descDe": "Gibt dem Verkehrsteilnehmer wichtige Verhaltenshinweise und Orientierungshilfen (Parkieren gestattet).",
    "descEn": "Provides motorists with operational roadway guidance and navigation assistance (Parking permitted).",
    "descFr": "Fournit aux usagers des indications utiles et des repères d'orientation (Parcage autorisé).",
    "descIt": "Fornisce agli utenti indicazioni utili e riferimenti di orientamento (Parcheggio)."
  },
  {
    "code": "4.18",
    "svg": "ch_4_18.svg",
    "group": "4",
    "catDe": "Hinweissignale",
    "catEn": "Information Signs",
    "catFr": "Signaux d'indication",
    "catIt": "Segnali d'indicazione",
    "article": "Art. 48",
    "nameDe": "Parkieren mit Parkscheibe",
    "nameEn": "Parking with parking disc",
    "nameFr": "Parcage avec disquede stationnement",
    "nameIt": "Parcheggio con disco",
    "descDe": "Erlaubt das Parkieren zeitlich beschränkt unter obligatorischer Verwendung der offiziellen blauen Schweizer Parkscheibe.",
    "descEn": "Permits time-limited parking under the mandatory display of the official blue Swiss parking disc.",
    "descFr": "Autorise le stationnement pour une durée limitée sous obligation d'utiliser le disque de stationnement bleu officiel suisse.",
    "descIt": "Consente la sosta limitata con l'obbligo di utilizzare il disco orario blu ufficiale svizzero."
  },
  {
    "code": "4.20",
    "svg": "ch_4_20.svg",
    "group": "4",
    "catDe": "Hinweissignale",
    "catEn": "Information Signs",
    "catFr": "Signaux d'indication",
    "catIt": "Segnali d'indicazione",
    "article": "Art. 48",
    "nameDe": "Parkieren gegen Gebühr",
    "nameEn": "Paid parking",
    "nameFr": "Parcage contrepaiement",
    "nameIt": "Parcheggio contro pagamento",
    "descDe": "Gibt dem Verkehrsteilnehmer wichtige Verhaltenshinweise und Orientierungshilfen (Parkieren gegen Gebühr).",
    "descEn": "Provides motorists with operational roadway guidance and navigation assistance (Paid parking).",
    "descFr": "Fournit aux usagers des indications utiles et des repères d'orientation (Parcage contrepaiement).",
    "descIt": "Fornisce agli utenti indicazioni utili e riferimenti di orientamento (Parcheggio contro pagamento)."
  },
  {
    "code": "4.35",
    "svg": "ch_4_35.svg",
    "group": "4",
    "catDe": "Hinweissignale",
    "catEn": "Information Signs",
    "catFr": "Signaux d'indication",
    "catIt": "Segnali d'indicazione",
    "article": "Art. 51",
    "nameDe": "Wegweiser in Tabellenform",
    "nameEn": "Table-style direction sign",
    "nameFr": "Indicateur de directionen forme de tableau",
    "nameIt": "Indicatore di direzione a forma di tabella",
    "descDe": "Zeigt bei Verzweigungen oder Anschlüssen Richtungs- und Fahrstreifeninformationen übersichtlich in Tabellenform an.",
    "descEn": "Displays lane assignments and destination directions systematically in a table layout at road junctions.",
    "descFr": "Indique de manière claire sous forme de tableau les directions et voies aux carrefours et jonctions.",
    "descIt": "Indica chiaramente in forma tabellare le direzioni e le corsie in corrispondenza di bivi e svincoli."
  },
  {
    "code": "5.01",
    "svg": "ch_5_01.svg",
    "group": "5",
    "catDe": "Zusatztafeln",
    "catEn": "Supplementary Panels",
    "catFr": "Plaques complémentaires",
    "catIt": "Tavole complementari",
    "article": "Art. 64",
    "nameDe": "Distanztafel",
    "nameEn": "Distance plate",
    "nameFr": "Plaque de distance",
    "nameIt": "Cartello di distanza",
    "descDe": "Ergänzt oder verdeutlicht übergeordnete Signale bzw. markiert Fahrbahnbegrenzungen (Distanztafel).",
    "descEn": "Complements road signage or provides pavement lane guidance (Distance plate).",
    "descFr": "Complète ou précise les signaux ou délimite les voies de circulation (Plaque de distance).",
    "descIt": "Completa o chiarisce i segnali principali o delimita le corsie (Cartello di distanza)."
  },
  {
    "code": "5.03",
    "svg": "ch_5_03.svg",
    "group": "5",
    "catDe": "Zusatztafeln",
    "catEn": "Supplementary Panels",
    "catFr": "Plaques complémentaires",
    "catIt": "Tavole complementari",
    "article": "Art. 64",
    "nameDe": "Streckenlänge",
    "nameEn": "Direction plate",
    "nameFr": "Longueur dutronçon",
    "nameIt": "Lunghezza del tratto",
    "descDe": "Ergänzt oder verdeutlicht übergeordnete Signale bzw. markiert Fahrbahnbegrenzungen (Streckenlänge).",
    "descEn": "Complements road signage or provides pavement lane guidance (Direction plate).",
    "descFr": "Complète ou précise les signaux ou délimite les voies de circulation (Longueur dutronçon).",
    "descIt": "Completa o chiarisce i segnali principali o delimita le corsie (Lunghezza del tratto)."
  },
  {
    "code": "5.07",
    "svg": "ch_5_07.svg",
    "group": "5",
    "catDe": "Zusatztafeln",
    "catEn": "Supplementary Panels",
    "catFr": "Plaques complémentaires",
    "catIt": "Tavole complementari",
    "article": "Art. 64",
    "nameDe": "Richtungstafel",
    "nameEn": "Heavy goods vehicle symbol",
    "nameFr": "Plaque dedirection",
    "nameIt": "Cartello di direzione",
    "descDe": "Ergänzt oder verdeutlicht übergeordnete Signale bzw. markiert Fahrbahnbegrenzungen (Richtungstafel).",
    "descEn": "Complements road signage or provides pavement lane guidance (Heavy goods vehicle symbol).",
    "descFr": "Complète ou précise les signaux ou délimite les voies de circulation (Plaque dedirection).",
    "descIt": "Completa o chiarisce i segnali principali o delimita le corsie (Cartello di direzione)."
  },
  {
    "code": "6.01",
    "svg": "ch_6_01.svg",
    "group": "6",
    "catDe": "Markierungen",
    "catEn": "Road Markings",
    "catFr": "Marquages routiers",
    "catIt": "Demarcazioni",
    "article": "Art. 73",
    "nameDe": "Sicherheitslinie",
    "nameEn": "Solid line (no crossing)",
    "nameFr": "Lignes de sécurité",
    "nameIt": "Linea di sicurezza",
    "descDe": "Ergänzt oder verdeutlicht übergeordnete Signale bzw. markiert Fahrbahnbegrenzungen (Sicherheitslinie).",
    "descEn": "Complements road signage or provides pavement lane guidance (Solid line (no crossing)).",
    "descFr": "Complète ou précise les signaux ou délimite les voies de circulation (Lignes de sécurité).",
    "descIt": "Completa o chiarisce i segnali principali o delimita le corsie (Linea di sicurezza)."
  },
  {
    "code": "6.02",
    "svg": "ch_6_02.svg",
    "group": "6",
    "catDe": "Markierungen",
    "catEn": "Road Markings",
    "catFr": "Marquages routiers",
    "catIt": "Demarcazioni",
    "article": "Art. 73",
    "nameDe": "Doppelte Sicherheitslinie6.03 Leitlinie",
    "nameEn": "Broken line (lane divider)",
    "nameFr": "Double ligne de sécurité6.03 Ligne de direction",
    "nameIt": "Doppia linea di sicurezza6.03 Linea di direzione",
    "descDe": "Ergänzt oder verdeutlicht übergeordnete Signale bzw. markiert Fahrbahnbegrenzungen (Doppelte Sicherheitslinie6.03 Leitlinie).",
    "descEn": "Complements road signage or provides pavement lane guidance (Broken line (lane divider)).",
    "descFr": "Complète ou précise les signaux ou délimite les voies de circulation (Double ligne de sécurité6.03 Ligne de direction).",
    "descIt": "Completa o chiarisce i segnali principali o delimita le corsie (Doppia linea di sicurezza6.03 Linea di direzione)."
  },
  {
    "code": "6.10",
    "svg": "ch_6_10.svg",
    "group": "6",
    "catDe": "Markierungen",
    "catEn": "Road Markings",
    "catFr": "Marquages routiers",
    "catIt": "Demarcazioni",
    "article": "Art. 75",
    "nameDe": "Haltelinie6.11 Stop6.12 Ununterbrochene Längslinie",
    "nameEn": "Stop line",
    "nameFr": "Ligne d’arrêt6.11 Stop6.12 Ligne longitudinale continue",
    "nameIt": "Linea di arresto6.11 Stop6.12 Linea longitudinale continua",
    "descDe": "Ergänzt oder verdeutlicht übergeordnete Signale bzw. markiert Fahrbahnbegrenzungen (Haltelinie6.11 Stop6.12 Ununterbrochene Längslinie).",
    "descEn": "Complements road signage or provides pavement lane guidance (Stop line).",
    "descFr": "Complète ou précise les signaux ou délimite les voies de circulation (Ligne d’arrêt6.11 Stop6.12 Ligne longitudinale continue).",
    "descIt": "Completa o chiarisce i segnali principali o delimita le corsie (Linea di arresto6.11 Stop6.12 Linea longitudinale continua)."
  },
  {
    "code": "6.13",
    "svg": "ch_6_13.svg",
    "group": "6",
    "catDe": "Markierungen",
    "catEn": "Road Markings",
    "catFr": "Marquages routiers",
    "catIt": "Demarcazioni",
    "article": "SSV Kat. 6.xx",
    "nameDe": "Unbekannt",
    "nameEn": "Give way line (shark teeth)",
    "nameFr": "Unbekannt",
    "nameIt": "Linea di attesa6.14 Preannuncio della linea di attesa",
    "descDe": "Ergänzt oder verdeutlicht übergeordnete Signale bzw. markiert Fahrbahnbegrenzungen (Unbekannt).",
    "descEn": "Complements road signage or provides pavement lane guidance (Give way line (shark teeth)).",
    "descFr": "Complète ou précise les signaux ou délimite les voies de circulation (Unbekannt).",
    "descIt": "Completa o chiarisce i segnali principali o delimita le corsie (Linea di attesa6.14 Preannuncio della linea di attesa)."
  },
  {
    "code": "6.17",
    "svg": "ch_6_17.svg",
    "group": "6",
    "catDe": "Markierungen",
    "catEn": "Road Markings",
    "catFr": "Marquages routiers",
    "catIt": "Demarcazioni",
    "article": "Art. 77",
    "nameDe": "Fussgängerstreifen6.18 Halteverbotslinie",
    "nameEn": "Pedestrian crossing markings",
    "nameFr": "Passage pour piétons6.18 Ligne interdisant l’arrêt",
    "nameIt": "Passaggio pedonale6.18 Linea vietante l’arresto",
    "descDe": "Ergänzt oder verdeutlicht übergeordnete Signale bzw. markiert Fahrbahnbegrenzungen (Fussgängerstreifen6.18 Halteverbotslinie).",
    "descEn": "Complements road signage or provides pavement lane guidance (Pedestrian crossing markings).",
    "descFr": "Complète ou précise les signaux ou délimite les voies de circulation (Passage pour piétons6.18 Ligne interdisant l’arrêt).",
    "descIt": "Completa o chiarisce i segnali principali o delimita le corsie (Passaggio pedonale6.18 Linea vietante l’arresto)."
  }
];
